### PR TITLE
Upgrade gridster.js to v0.5.1

### PR DESCRIPTION
**Pull request by liln**
I upgraded the version of gridster from v0.1.0 to the most recent production version. Feel free to merge if you would like.

### CODE REVIEW

**Comment by wolfspyre** [comment]
It would indeed be great! I notice gridster is now at [0.5.6](https://github.com/ducksboard/gridster.js). What's preventing an updated version of this from being added to the next release?

**Comment by tylermauthe** [comment]
Are there any breaking changes in this update? Or in the update to 0.5.6?

**Comment by pushmatrix** [comment]
This looks good to me. I tried it out and it didn't seem to have any breaking changes. Thanks!

**Comment by pushmatrix** [comment]
@wolfspyre Feel free to create PR for 0.5.6 :)

**Pull request merged**
