### PR TITLE
Update Dashing to use FontAwesome 4.3.0

### PR DESCRIPTION
**Pull request by jmb**
This pull request is the update to FontAwesome 4.3.0.

I have replaced the font files and fontawesome css file (with a minor update for the paths to the fonts).
I have updated the few places that the old `icon-` fontawesome class names were used with the new `fa-` format (and the changed icon names as appropriate).

Please let me know if I've missed anything, but this should mean the base install of Dashing works fine - 3rd party widgets may need updating to use the new FontAwesome class names.

### CODE REVIEW

**Comment by tylermauthe** [comment]
Hope this gets merged :+1:

**Comment by tylermauthe** [comment]
This would have breaking changes -- but the migration path is likely a simple Find All & Replace.

**Comment by MartynKeigher** [comment]
Pardon my ignorance here (probably a simple Q) but... has this been merged into the master yet? and if not.. whats the easiest way to implement it?

I'm looking to re-install my dashing VM, and I remember there was "a lot of find and replace" to get this rolling! Is this still the case today, or has something more streamlined been introduced, since this happened in February? 

Thanks.

**Comment by tylermauthe** [comment]
This hasn't been merged.

If you install the dashing gem from that fork, you should be up and rolling with the latest font-awesome.

If you had any custom widgets, they would need to be updated to use the new `fa-` prefixes. This is the main concern with merging this PR, is that 3rd party widgets would need to be updated.

However, we will eventually need to do this...

**Comment by jmb** [comment]
A year on and no merge! :-1: 

This pull request is out of date itself now as FontAwesome is now at version 4.5.0!

**Comment by jmb** [comment]
Superseded by new PR #687 for FontAwesome 4.5.0

**Pull request closed without merging**
