### PR TITLE
Use redis for history on Heroku

### PR DESCRIPTION
**Pull request by bitle**
Enable `redis` to persist history on Heroku.

### CODE REVIEW

**Comment by tylermauthe** [comment]
This PR seems to try to load history from Redis but I don't see where it is saving the history to Redis.

You'll probably want to add some code to do this around in this block:
https://github.com/Shopify/dashing/blob/937fcce2dcca8010dbe8e9e26df954cb1330c1e0/lib/dashing/app.rb#L56-L58

**Comment by pushmatrix** [comment]
I'd rather not add a dependency on redis gems. I'd prefer if this functionality could be added as a separate gem. Something like `dashing-redis`.

**Comment by and7ey** [comment]
Will appreciate if somebody would publish a wiki article with step-by-step tutorial how to enable redis usage (I did something, but not sure if it works correctly... first time use Ruby app). Believe, it will help other users too.

**Comment by and7ey** [comment]
The code given in the commit doesn't work well when both `history.yml` exists and `Redis` supported: 

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:334:in `path2class': undefined class/module Redis:: (ArgumentError)

**Pull request closed without merging**
