### PR TITLE
Ignore log directory

### PR DESCRIPTION
**Pull request by kassi**

### CODE REVIEW

**Comment by tylermauthe** [comment]
+1 to this... I'd also recommend adding history.yml and tmp/

Thoughts?

**Comment by kassi** [comment]
Sure. I added tmp locally later without checking it in, but history.yml is a good point. Added!

**Comment by tylermauthe** [comment]
I do this on every Dashing project -- probably a sensible default. :+1: for merging.

**Comment by pushmatrix** [comment]
Yeehaa!

**Pull request merged**
