### PR TITLE
Update to use FontAwesome 4.5.0

### PR DESCRIPTION
**Pull request by jmb**
Similar to PR #514 this is now an update to FontAwesome 4.5.0

### CODE REVIEW

**Comment by jmb** [comment]
See comments on #514, but I have made the same changes as before just with the new FA package:

I have replaced the font files and fontawesome css file (with a minor update for the paths to the fonts).
I have updated the few places that the old icon- fontawesome class names were used with the new fa- format (and the changed icon names as appropriate).

Please let me know if I've missed anything, but this should mean the base install of Dashing works fine - 3rd party widgets may need updating to use the new FontAwesome _fa_ class names - **this should be a simple find-and-replace**.

**Comment by howardsternisbatman** [comment]
It's that time again. Thanks for making the update...where can I grab the files from :)?

**Comment by jmb** [comment]
Just merge from my repository's fontawesome-4.5.0 branch, the same as before. :smile:

**Comment by pushmatrix** [comment]
Thanks for you help with this @jmb!

**Pull request merged**
